name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '^16.3'
      - run: npm ci
      - run: npm run lint
      - run: npm run lint:style
      # add lint here
      - run: npm run build
